/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Configs {
  created_at: Timestamp;
  id: string;
  name: string;
  updated_at: Timestamp;
  value: Json;
  version: number;
}

export interface Migrations {
  id: number;
  runat: Timestamp;
  sql: string;
}

export interface DB {
  configs: Configs;
  migrations: Migrations;
}
