/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type {ColumnType} from 'kysely';

export type ConfigProposalRejectionReason =
  | 'another_proposal_approved'
  | 'config_deleted'
  | 'config_edited'
  | 'rejected_explicitly';

export type ConfigUserRole = 'editor' | 'maintainer';

export type Generated<T> =
  T extends ColumnType<infer S, infer I, infer U>
    ? ColumnType<S, I | undefined, U>
    : ColumnType<T, T | undefined, T>;

export type Int8 = ColumnType<string, bigint | number | string, bigint | number | string>;

export type ProjectUserRole = 'admin' | 'maintainer';

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export type WorkspaceMemberRole = 'admin' | 'member';

export interface Accounts {
  access_token: string | null;
  expires_at: Int8 | null;
  id: Generated<number>;
  id_token: string | null;
  provider: string;
  providerAccountId: string;
  refresh_token: string | null;
  scope: string | null;
  session_state: string | null;
  token_type: string | null;
  type: string;
  userId: number;
}

export interface AuditLogs {
  config_id: string | null;
  created_at: Timestamp;
  environment_id: string | null;
  id: string;
  payload: string;
  project_id: string | null;
  user_id: number | null;
}

export interface ConfigProposals {
  approved_at: Timestamp | null;
  base_config_version: number;
  config_id: string;
  created_at: Timestamp;
  id: string;
  message: string | null;
  original_description: string;
  original_members: string;
  proposed_delete: boolean;
  proposed_description: string;
  proposed_members: string;
  proposer_id: number | null;
  rejected_at: Timestamp | null;
  rejected_in_favor_of_proposal_id: string | null;
  rejection_reason: ConfigProposalRejectionReason | null;
  reviewer_id: number | null;
}

export interface ConfigProposalVariants {
  config_variant_id: string;
  environment_id: string | null;
  id: string;
  proposal_id: string;
  proposed_overrides: string;
  proposed_schema: string | null;
  proposed_value: string;
  use_default_schema: boolean;
}

export interface Configs {
  created_at: Timestamp;
  creator_id: number;
  description: string;
  id: string;
  name: string;
  project_id: string;
  updated_at: Timestamp;
  version: number;
}

export interface ConfigUsers {
  config_id: string;
  created_at: Timestamp;
  role: ConfigUserRole;
  updated_at: Timestamp;
  user_email_normalized: string;
}

export interface ConfigVariants {
  config_id: string;
  created_at: Timestamp;
  environment_id: string | null;
  id: string;
  overrides: string;
  schema: string | null;
  updated_at: Timestamp;
  use_default_schema: Generated<boolean>;
  value: string;
}

export interface ConfigVariantVersions {
  author_id: number | null;
  config_variant_id: string;
  created_at: Timestamp;
  description: string;
  id: string;
  name: string;
  overrides: string;
  proposal_id: string | null;
  schema: string | null;
  value: string;
  version: number;
}

export interface EventConsumers {
  created_at: Timestamp;
  id: Generated<Int8>;
  last_used_at: Timestamp;
}

export interface Events {
  consumer_id: Int8;
  created_at: Timestamp;
  data: string;
  id: Generated<Int8>;
}

export interface Migrations {
  id: number;
  runat: Timestamp;
  sql: string;
}

export interface ProjectEnvironments {
  created_at: Timestamp;
  id: string;
  name: string;
  order: Generated<number>;
  project_id: string;
  updated_at: Timestamp;
}

export interface Projects {
  allow_self_approvals: boolean;
  created_at: Timestamp;
  description: string;
  id: string;
  is_example: Generated<boolean>;
  name: string;
  require_proposals: boolean;
  updated_at: Timestamp;
  workspace_id: string;
}

export interface ProjectUsers {
  created_at: Timestamp;
  project_id: string;
  role: ProjectUserRole;
  updated_at: Timestamp;
  user_email_normalized: string;
}

export interface SdkKeys {
  created_at: Timestamp;
  creator_id: number;
  description: string;
  environment_id: string;
  id: string;
  name: string;
  project_id: string;
  token_hash: string;
}

export interface Sessions {
  expires: Timestamp;
  id: Generated<number>;
  sessionToken: string;
  userId: number;
}

export interface Users {
  email: string | null;
  emailVerified: Timestamp | null;
  id: Generated<number>;
  image: string | null;
  name: string | null;
}

export interface VerificationToken {
  expires: Timestamp;
  identifier: string;
  token: string;
}

export interface WorkspaceMembers {
  created_at: Timestamp;
  role: WorkspaceMemberRole;
  updated_at: Timestamp;
  user_email_normalized: string;
  workspace_id: string;
}

export interface Workspaces {
  auto_add_new_users: Generated<boolean>;
  created_at: Timestamp;
  id: string;
  name: string;
  personal_workspace_user_id: number | null;
  updated_at: Timestamp;
}

export interface DB {
  accounts: Accounts;
  audit_logs: AuditLogs;
  config_proposal_variants: ConfigProposalVariants;
  config_proposals: ConfigProposals;
  config_users: ConfigUsers;
  config_variant_versions: ConfigVariantVersions;
  config_variants: ConfigVariants;
  configs: Configs;
  event_consumers: EventConsumers;
  events: Events;
  migrations: Migrations;
  project_environments: ProjectEnvironments;
  project_users: ProjectUsers;
  projects: Projects;
  sdk_keys: SdkKeys;
  sessions: Sessions;
  users: Users;
  verification_token: VerificationToken;
  workspace_members: WorkspaceMembers;
  workspaces: Workspaces;
}
